### ISSUE TITLE
Api calls are failing.

### ISSUE THREAD

**Issue by MAKOSCAFEE** [hisptz/ngx-dhis2-menu#1]
i have tried including the library in other project and looks like api calls are failing due to `CORS` issue.
<img width="1679" alt="screen shot 2018-06-23 at 18 07 51" src="https://user-images.githubusercontent.com/6409210/41811033-88de237c-7710-11e8-9f00-b17fbaa0c541.png">

**Comment by rajey** [comment]
Those Apis are failing in development environment only. Perhaps try to add your localhost address in the `CORS` whitelist so it removes the error.
